---

- hosts: crayfish
  become: yes

  vars:
    php_version: "7.2"

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - name: geerlingguy.mysql
      when: claw_db == 'mysql'
    - name: geerlingguy.postgresql
      when: claw_db == 'pgsql'
    - Islandora-Devops.crayfish
