---

- hosts: webserver
  become: yes

  vars:
    php_version: "7.2"

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - geerlingguy.drupal
    - Islandora-Devops.drupal-openseadragon
    - webserver-app
    - name: geerlingguy.mysql
      when: claw_db == 'mysql'
    - name: geerlingguy.postgresql
      when: claw_db == 'pgsql'
    - Islandora-Devops.matomo
